/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <SecondTimer.h>
#include <SecondTimer_clock.h>
#include <LED4_aliases.h>
#include <LED4.h>
#include <Display.h>
#include <Stopwatch.h>
#include <Stopwatch_clock.h>
#include <StopwatchReset.h>
#include <SW3_StopwatchStop_aliases.h>
#include <SW3_StopwatchStop.h>
#include <SW2_StopwatchStart_aliases.h>
#include <SW2_StopwatchStart.h>
#include <StopwatchStopISR.h>
#include <StopwatchStartISR.h>
#include <DisplayRefresh.h>
#include <DisplayRefreshISR.h>
#include <Display_LCDPort_aliases.h>
#include <Display_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

