/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Audio_Pin_aliases.h>
#include <Audio_Pin.h>
#include <VoiceA_DAC.h>
#include <EnvelopeControl.h>
#include <Envelope_timer.h>
#include <Display.h>
#include <emFile.h>
#include <SW2_aliases.h>
#include <SW2.h>
#include <SW3_aliases.h>
#include <SW3.h>
#include <Pushbuttons.h>
#include <RefreshInterval_isr.h>
#include <VoiceB_DAC.h>
#include <VoiceC_DAC.h>
#include <Audio_opamp.h>
#include <VoiceC_Amplitude.h>
#include <VoiceB_Amplitude.h>
#include <Mixer_Control.h>
#include <VoiceA_Amplitude.h>
#include <VoiceC_clock.h>
#include <VoiceB_clock.h>
#include <EnvelopeReset.h>
#include <VoiceA_clock.h>
#include <Reset_clock.h>
#include <Noise_clock.h>
#include <NoiseGenerator.h>
#include <Display_LCDPort_aliases.h>
#include <Display_LCDPort.h>
#include <emFile_SPI0.h>
#include <emFile_SPI0_PVT.h>
#include <emFile_mosi0_aliases.h>
#include <emFile_mosi0.h>
#include <emFile_Clock_1.h>
#include <emFile_miso0_aliases.h>
#include <emFile_miso0.h>
#include <emFile_sclk0_aliases.h>
#include <emFile_sclk0.h>
#include <emFile_SPI0_CS_aliases.h>
#include <emFile_SPI0_CS.h>
#include <CyRefreshInterval_clock.h>
#include <CySYNTH_MASTER_CLK.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

